kind: Deployment
apiVersion: apps/v1
metadata:
  name: pg-test-app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: pg-test-app
  template:
    metadata:
      name: pg-test-app
      labels:
        name: pg-test-app
    spec:
      containers:
        - name: pg-test-app
          image: mcyprian/pg-replication-test:0.0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            timeoutSedonds: 3
            initialDelaySeconds: 3
            httpGet:
              path: /healthz
              port: 8080
          livelinessProbe:
             timeoutSedonds: 3
             initialDelaySeconds: 30
             httpGet:
               path: /healthz
               port: 8080
          env:
            - name: DATABASE_SERVICE_NAME
              value: ${DATABASE_SERVICE_NAME}
            - name: DATABASE_ENGINE
              value: ${DATABASE_ENGINE}
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-master
                  key: database-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: pg-master
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-master
                  key: database-password
          resources:
            limits:
              memory: 256Mi
